# Generated by Django 5.1.2 on 2024-10-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
