# Generated by Django 5.1.2 on 2024-11-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='mail',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
